### ISSUE TITLE
question: slice of subs instead of map

### ISSUE THREAD

**Issue by oliverpool** [peterbourgon/ps#1]
Hi, your library looks very well thought-out!

I have a question, regarding the internal storage of `subs`. Did you consider using a slice of `[]*subscriber[T]` instead of a `map[chan<- T]*subscriber[T]`?

Instead of 
https://github.com/peterbourgon/ps/blob/1e3d0ad6a1ce682bdfec443e4daa24d9b561b428/broker.go#L11-L14

have:
```go
type Broker[T any] struct {
	mtx  sync.Mutex
	subs []*subscriber[T]
}

type subscriber[T any] struct {
	ch chan<- T
	allow func(T) bool
	stats Stats
}
```

---

This should greatly simplify (and accelerate?) the `ActiveSubscribers` logic (since ranging of the slice will always yield stable results). It will even be predictable (the first stats is for the first subscriber).
The main downside, is that it could slow down a bit the `Subscribe`, `Unsubscribe` and `Stats` logic (but as long as the number of subscribers is reasonable, it shouldn't change much).

I would love to read your opinion on the subject!

**Comment by peterbourgon** [comment]
ActiveSubscribers is basically a diagnostic function, mostly useful in tests, not really worth optimizing for 😅 

I think it's pretty important that subscribers are directly addressable.

**Comment by oliverpool** [comment]
That makes sense, thank you!

It is probably worth benchmarking, because map appear to have a non-negligible overhead when the number of elements is under 10 (subscribing is likely faster and publishing is surely faster with a slice)

**Comment by peterbourgon** [comment]
Will do!
